// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: whether.proto

package golang

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionProcessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromChatId int64  `protobuf:"varint,1,opt,name=from_chat_id,json=fromChatId,proto3" json:"from_chat_id,omitempty"`
	Action     string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *ActionProcessRequest) Reset() {
	*x = ActionProcessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_whether_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionProcessRequest) ProtoMessage() {}

func (x *ActionProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whether_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionProcessRequest.ProtoReflect.Descriptor instead.
func (*ActionProcessRequest) Descriptor() ([]byte, []int) {
	return file_whether_proto_rawDescGZIP(), []int{0}
}

func (x *ActionProcessRequest) GetFromChatId() int64 {
	if x != nil {
		return x.FromChatId
	}
	return 0
}

func (x *ActionProcessRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_whether_proto protoreflect.FileDescriptor

var file_whether_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x77, 0x68, 0x65, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x77, 0x68, 0x65, 0x74, 0x68, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x14, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x51, 0x0a, 0x07, 0x57, 0x68, 0x65, 0x74, 0x68,
	0x65, 0x72, 0x12, 0x46, 0x0a, 0x0d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x1d, 0x2e, 0x77, 0x68, 0x65, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x75, 0x72, 0x61, 0x73, 0x68, 0x6f,
	0x76, 0x56, 0x65, 0x6e, 0x2f, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x72, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x68, 0x65, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_whether_proto_rawDescOnce sync.Once
	file_whether_proto_rawDescData = file_whether_proto_rawDesc
)

func file_whether_proto_rawDescGZIP() []byte {
	file_whether_proto_rawDescOnce.Do(func() {
		file_whether_proto_rawDescData = protoimpl.X.CompressGZIP(file_whether_proto_rawDescData)
	})
	return file_whether_proto_rawDescData
}

var file_whether_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_whether_proto_goTypes = []interface{}{
	(*ActionProcessRequest)(nil), // 0: whether.ActionProcessRequest
	(*emptypb.Empty)(nil),        // 1: google.protobuf.Empty
}
var file_whether_proto_depIdxs = []int32{
	0, // 0: whether.Whether.ActionProcess:input_type -> whether.ActionProcessRequest
	1, // 1: whether.Whether.ActionProcess:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_whether_proto_init() }
func file_whether_proto_init() {
	if File_whether_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_whether_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionProcessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_whether_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whether_proto_goTypes,
		DependencyIndexes: file_whether_proto_depIdxs,
		MessageInfos:      file_whether_proto_msgTypes,
	}.Build()
	File_whether_proto = out.File
	file_whether_proto_rawDesc = nil
	file_whether_proto_goTypes = nil
	file_whether_proto_depIdxs = nil
}
